# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
