# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_tracker', '0002_auto_20190926_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('repair_status', models.CharField(choices=[('to do', 'TODO'), ('doing', 'DOING'), ('done', 'DONE')], default='to do', max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votes', models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='i_have_this_too',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bugs',
        ),
        migrations.AddField(
            model_name='comment',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.Bug'),
        ),
    ]
