# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-28 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20191222_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='i_have_this_too',
        ),
    ]
