# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20191001_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('to do', 'TODO'), ('doing', 'DOING'), ('done', 'DONE')], default='to do', max_length=6),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
