# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_auto_20191007_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
