# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_auto_20191113_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to=settings.AUTH_USER_MODEL),
        ),
    ]
