# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='user',
            new_name='author',
        ),
    ]
