# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0006_auto_20191115_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='votes',
        ),
        migrations.AddField(
            model_name='feature',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='feature_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
