# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191016_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('undefined', 'UNDEFINED'), ('female', 'FEMALE'), ('male', 'MALe')], default='undefined', max_length=6),
        ),
    ]
