# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191218_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('undefined', 'UNDEFINED'), ('female', 'FEMALE'), ('male', 'MALE')], default='', max_length=12),
        ),
    ]
