# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191022_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('undefined', 'UNDEFINED'), ('female', 'FEMALE'), ('male', 'MALE')], default='undefined', max_length=6),
        ),
    ]
