# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
    ]
